import { z } from "zod";
import { router } from "../trpc.js";
import { privateProcedure, publicProcedure } from "../procedures/index.js";
import { ProposalInputZ, ProposalOutputZ, proposalEngine, type ProposalOutput } from "@repo/validators";

export const proposalRouter = router({
  /**
   * Create a new proposal
   */
  create: privateProcedure
    .input(ProposalInputZ)
    .output(ProposalOutputZ)
    .mutation(async ({ input, ctx }) => {
      // Process proposal through engine (STUB)
      const processedProposal = await proposalEngine.processProposal(input);
      
      // Save to database
      const savedProposal = await ctx.db.proposal.create({
        data: {
          id: processedProposal.id,
          title: processedProposal.title,
          summary: processedProposal.summary,
          category: processedProposal.category.toUpperCase() as any,
          proposerWallet: processedProposal.proposer.wallet,
          proposerRole: processedProposal.proposer.role.toUpperCase() as any,
          proposerDisplayName: processedProposal.proposer.displayName,
          regionCode: processedProposal.region.code,
          regionName: processedProposal.region.name,
          budgetCurrency: processedProposal.budget.currency.toUpperCase() as any,
          budgetAmount: processedProposal.budget.amountRequested,
          localPercent: processedProposal.treasuryPlan.localPercent,
          nationalPercent: processedProposal.treasuryPlan.nationalPercent,
          acceptUC: processedProposal.treasuryPlan.acceptUC,
          leakageReductionUSD: processedProposal.impact.leakageReductionUSD,
          jobsCreated: processedProposal.impact.jobsCreated,
          timeHorizonMonths: processedProposal.impact.timeHorizonMonths,
          alignmentScore: processedProposal.scores.alignment,
          feasibilityScore: processedProposal.scores.feasibility,
          compositeScore: processedProposal.scores.composite,
          quorumPercent: processedProposal.governance.quorumPercent,
          approvalThresholdPercent: processedProposal.governance.approvalThresholdPercent,
          votingWindowDays: processedProposal.governance.votingWindowDays,
          engineVersion: processedProposal.audit.engineVersion,
          status: processedProposal.status.toUpperCase() as any,
          auditChecks: {
            createMany: {
              data: processedProposal.audit.checks.map((check: any) => ({
                name: check.name,
                passed: check.passed,
                note: check.note
              }))
            }
          }
        },
        include: {
          kpis: true,
          auditChecks: true
        }
      });

      // Create KPIs from processed proposal if they exist
      // Note: KPIs are now generated by the AI agents, not provided in input
      // This section can be removed or updated based on future KPI handling

      // Fetch complete proposal with KPIs
      const completeProposal = await ctx.db.proposal.findUnique({
        where: { id: savedProposal.id },
        include: {
          kpis: true,
          auditChecks: true
        }
      });
      
      return mapDbToOutput(completeProposal);
    }),

  /**
   * Get proposal by ID
   */
  getById: publicProcedure
    .input(z.object({ id: z.string() }))
    .output(ProposalOutputZ.nullable())
    .query(async ({ input, ctx }) => {
      const proposal = await ctx.db.proposal.findUnique({
        where: { id: input.id },
        include: {
          kpis: true,
          auditChecks: true
        }
      });
      
      if (!proposal) return null;
      
      return mapDbToOutput(proposal);
    }),

  /**
   * List proposals with filtering and pagination
   */
  list: publicProcedure
    .input(z.object({
      status: z.enum(["draft", "votable", "approved", "funded", "rejected"]).optional(),
      category: z.enum([
        "business_funding", "procurement", "infrastructure", "transport",
        "wallet_incentive", "governance", "other"
      ]).optional(),
      region: z.string().optional(),
      limit: z.number().min(1).max(100).default(20),
      offset: z.number().min(0).default(0)
    }))
    .output(z.object({
      proposals: z.array(ProposalOutputZ as any),
      total: z.number(),
      hasMore: z.boolean()
    }))
    .query(async ({ input, ctx }) => {
      const where = {
        ...(input.status && { status: input.status.toUpperCase() as any }),
        ...(input.category && { category: input.category.toUpperCase() as any }),
        ...(input.region && { regionCode: input.region })
      };
      
      const [proposals, total] = await Promise.all([
        ctx.db.proposal.findMany({
          where,
          skip: input.offset,
          take: input.limit,
          orderBy: { createdAt: 'desc' },
          include: {
            kpis: true,
            auditChecks: true
          }
        }),
        ctx.db.proposal.count({ where })
      ]);
      
      return {
        proposals: proposals.map(mapDbToOutput),
        total,
        hasMore: input.offset + input.limit < total
      };
    }),

  /**
   * Update proposal status (admin/system only)
   */
  updateStatus: privateProcedure
    .input(z.object({
      id: z.string(),
      status: z.enum(["draft", "votable", "approved", "funded", "rejected"])
    }))
    .output(ProposalOutputZ)
    .mutation(async ({ input, ctx }) => {
      // TODO: Implement authorization check
      // TODO: Update database
      // TODO: Return updated proposal
      
      throw new Error("Not implemented");
    }),

  /**
   * Get proposals by proposer wallet
   */
  getByProposer: publicProcedure
    .input(z.object({ 
      wallet: z.string(),
      limit: z.number().min(1).max(50).default(10),
      offset: z.number().min(0).default(0)
    }))
    .output(z.object({
      proposals: z.array(ProposalOutputZ as any),
      total: z.number()
    }))
    .query(async ({ input, ctx }) => {
      const [proposals, total] = await Promise.all([
        ctx.db.proposal.findMany({
          where: { proposerWallet: input.wallet },
          skip: input.offset,
          take: input.limit,
          orderBy: { createdAt: 'desc' },
          include: {
            kpis: true,
            auditChecks: true
          }
        }),
        ctx.db.proposal.count({
          where: { proposerWallet: input.wallet }
        })
      ]);
      
      return {
        proposals: proposals.map(mapDbToOutput),
        total
      };
    }),

  /**
   * Get proposals by region
   */
  getByRegion: publicProcedure
    .input(z.object({
      regionCode: z.string(),
      limit: z.number().min(1).max(50).default(10),
      offset: z.number().min(0).default(0)
    }))
    .output(z.object({
      proposals: z.array(ProposalOutputZ as any),
      total: z.number()
    }))
    .query(async ({ input, ctx }) => {
      const [proposals, total] = await Promise.all([
        ctx.db.proposal.findMany({
          where: { regionCode: input.regionCode },
          skip: input.offset,
          take: input.limit,
          orderBy: { createdAt: 'desc' },
          include: {
            kpis: true,
            auditChecks: true
          }
        }),
        ctx.db.proposal.count({
          where: { regionCode: input.regionCode }
        })
      ]);
      
      return {
        proposals: proposals.map(mapDbToOutput),
        total
      };
    }),

  /**
   * Test endpoint to verify engine functionality
   */
  testEngine: publicProcedure
    .output(ProposalOutputZ)
    .query(async () => {
      // Test data using the new simplified text-only input
      const testInput = {
        text: "Hampton Grocery Anchor: Fund a small-format grocery to reduce external food spend and increase UC usage. Budget needed: $150,000 USD. Located in Hampton Roads, VA. Expected to reduce economic leakage by $1,000,000 annually and create 12 jobs over 12 months. Target 750,000 USD in local spend retained and 200,000 UC in transactions.",
        proposer: { wallet: "0xabc123", role: "bot" as const, displayName: "SuggestionBot" },
        region: { code: "VA-HAMPTON", name: "Hampton Roads, VA" },
      };

      return proposalEngine.processProposal(testInput);
    })
});

// Helper function to map database records to output format
function mapDbToOutput(dbRecord: any): ProposalOutput {
  return {
    id: dbRecord.id,
    createdAt: dbRecord.createdAt.toISOString(),
    status: dbRecord.status.toLowerCase(),
    title: dbRecord.title,
    summary: dbRecord.summary,
    category: dbRecord.category.toLowerCase(),
    proposer: {
      wallet: dbRecord.proposerWallet,
      role: dbRecord.proposerRole.toLowerCase(),
      displayName: dbRecord.proposerDisplayName
    },
    region: {
      code: dbRecord.regionCode,
      name: dbRecord.regionName
    },
    budget: {
      currency: dbRecord.budgetCurrency.toLowerCase(),
      amountRequested: dbRecord.budgetAmount
    },
    treasuryPlan: {
      localPercent: dbRecord.localPercent,
      nationalPercent: dbRecord.nationalPercent,
      acceptUC: dbRecord.acceptUC
    },
    impact: {
      leakageReductionUSD: dbRecord.leakageReductionUSD,
      jobsCreated: dbRecord.jobsCreated,
      timeHorizonMonths: dbRecord.timeHorizonMonths
    },
    scores: {
      alignment: dbRecord.alignmentScore,
      feasibility: dbRecord.feasibilityScore,
      composite: dbRecord.compositeScore
    },
    governance: {
      quorumPercent: dbRecord.quorumPercent,
      approvalThresholdPercent: dbRecord.approvalThresholdPercent,
      votingWindowDays: dbRecord.votingWindowDays
    },
    audit: {
      engineVersion: dbRecord.engineVersion,
      checks: dbRecord.auditChecks.map((check: any) => ({
        name: check.name,
        passed: check.passed,
        note: check.note
      }))
    }
  };
}