#!/usr/bin/env node

/**
 * Roadmap Bot Configuration
 * This file contains all configuration for the multi-agent roadmap monitoring system.
 * Copy this file to other codebases and adjust settings as needed.
 */

const config = {
  // Core settings
  roadmapFile: 'documents/tech_roadmap.md',
  confidenceThreshold: 85,
  
  // OpenAI settings
  model: {
    analysis: 'gpt-4o-mini',    // For roadmap analysis and matching
    autofix: 'gpt-4o-mini',     // For simple auto-fixes
    complex: 'gpt-4'            // For complex operations (use sparingly)
  },
  
  // Auto-fix complexity limits
  autofix: {
    enabled: true,
    maxFilesChanged: 3,
    maxLinesPerFile: 20,
    maxTotalLines: 50,
    allowedFileTypes: ['.md', '.json', '.js', '.ts', '.tsx', '.jsx', '.yml', '.yaml'],
    disallowedPatterns: [
      /auth/i,
      /security/i,
      /database/i,
      /migration/i,
      /config\/production/i,
      /\.env/i
    ],
    safeOperations: [
      'documentation',
      'comments',
      'imports',
      'exports',
      'dependencies',
      'configuration',
      'types',
      'tests'
    ]
  },
  
  // GitHub settings
  github: {
    maxPRCommentsPerRun: 1,
    branchPrefix: 'roadmap-bot/',
    labels: {
      roadmapMatch: 'roadmap-match',
      autoGenerated: 'bot-generated',
      needsReview: 'needs-review'
    }
  },
  
  // Agent behavior
  agents: {
    roadmapAnalyzer: {
      name: 'RoadmapAnalyzer',
      systemPrompt: `You are a technical roadmap analysis expert. Your job is to analyze Pull Request changes and determine if they solve or partially solve items in the project's technical roadmap.

You must be precise and technical in your analysis. Focus on:
- Code functionality and technical implementation
- Infrastructure and architecture changes  
- Feature completions and technical milestones
- NOT product features or business requirements

Return ONLY valid JSON in this exact format:
{
  "matches": [
    {
      "roadmapItem": "exact text from roadmap",
      "confidence": 85,
      "reasoning": "technical explanation of why this matches",
      "completionLevel": "full|partial",
      "suggestedMarkdown": "~~crossed out text~~"
    }
  ]
}

If no technical matches found, return: {"matches": []}`,
      maxTokens: 800,
      temperature: 0.2
    },
    
    completionSuggester: {
      name: 'CompletionSuggester',
      systemPrompt: `You are a technical roadmap strategist. When a PR completes a roadmap item, suggest specific technical sub-items for remaining roadmap items.

Focus on obvious technical needs like:
- Testing requirements
- Documentation needs
- Integration requirements
- Performance considerations
- Security implementations
- Error handling
- Monitoring/logging

Be specific and technical. Avoid product/business suggestions.

Return ONLY valid JSON:
{
  "suggestions": [
    {
      "parentItem": "roadmap item text",
      "subItems": ["specific technical task 1", "specific technical task 2"],
      "priority": "high|medium|low",
      "reasoning": "why these sub-items are needed now"
    }
  ]
}`,
      maxTokens: 1000,
      temperature: 0.3
    },
    
    autoFixer: {
      name: 'AutoFixer',
      systemPrompt: `You are a careful code automation agent. Your job is to implement ONLY simple, safe technical changes for roadmap items.

ONLY attempt changes that are:
- Documentation updates
- Simple configuration changes
- Adding missing imports/types
- Basic dependency updates
- Simple test additions
- Comment additions

NEVER attempt:
- Authentication/security changes
- Database modifications
- Complex business logic
- Multi-file architectural changes

Return ONLY valid JSON:
{
  "canFix": true|false,
  "confidence": 85,
  "changes": [
    {
      "file": "path/to/file",
      "action": "create|modify|delete",
      "description": "what will be changed",
      "content": "new file content or null for modifications"
    }
  ],
  "reasoning": "why this is safe to automate"
}

If unsure or complex, return: {"canFix": false, "reasoning": "explanation"}`,
      maxTokens: 1200,
      temperature: 0.1
    }
  }
};

module.exports = config;