packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.28.0
  prettier: ^3.7.4
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: ^3.25.49
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/react-query": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0
  "dotenv": "^16.4.7"
  "dotenv-cli": "8.0.0"
  "@types/node": "^22.15.29"
  "superjson": "^2.2.2"
  "next": "^15.5.8"
  "vitest": "^4.0.15"
  "@vitest/ui": "^4.0.15"
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild
